spring:
  # SQL Server Database Configuration ------------------------
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=scontrack;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Password1
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
# ----------------------------------------------------------

# Telegram BOT Configuration -------------------------------
telegram:
  token: 6867808049:AAEHutFRy-z0Eq1Nqq4Y0TFoh6NO9I_EEZc
  bot-name: scontrack
# ----------------------------------------------------------

azure:
  blob-storage:
    connection: DefaultEndpointsProtocol=https;AccountName=scontracksa;AccountKey=G7hKoGZ0u4ZXVSJOngEzRzJuNSr1YqKwGtSGSMzg0QPsaYYvbG3Cr2vxC+uaLDVPPEiS7AwKqbKA+ASt06uv+w==;EndpointSuffix=core.windows.net
  blob-storage-endpoint: https://scontrack.blob.core.windows.net/scontrack-images/
  receipt-ai-analyzer: https://scontrack-receipt-analyzer.azurewebsites.net/api/recepit_analyzer?code=9H3CLgzStMQmBeKVaoZ5M5sqCDxOh8QP8BQswy-miGX1AzFukF99Pg==